### PR TITLE
Prepare new release (not yet due)

### PR DESCRIPTION
**Pull request by hsonne**
found with extdata/cleanCodeBasics.R in kwb.code!

### CODE REVIEW

**Review by hsonne — COMMENTED** [review]
we are safe: the server does not exist any more!

**Comment by mrustl** [comment]
ah ok so my tried fix is useless? https://github.com/KWB-R/kwb.misc/pull/3/commits/f05c916da90f1e36c9df51cd45bc4162ac1fc2fb

**Comment by hsonne** [comment]
No, it's 🚀 but 🐋 is dead.

**Comment by hsonne** [comment]
@mrustl What is the problem, I added GITHUB_PAT but still failure:
https://github.com/KWB-R/kwb.misc/runs/6783288149?check_suite_focus=true

**Comment by mrustl** [comment]
Too many workflows in too many repos were started in  parallel.....restarted the ones from master manually just now!

**Pull request merged**
